version: '3.8'

services:
  example-frontend:
    build:
      context: ./example-frontend

  example-backend:
    build:
      context: ./example-backend
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: example

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: postgres
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data

  redmine:
    image: redmine:4.1-alpine
    environment:
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_PASSWORD=example
    ports:
      - 9999:3000
    depends_on:
      - db

  # adminer:
  #   image: adminer:4
  #   restart: always
  #   environment:
  #     - ADMINER_DESIGN=galkaev
  #   ports:
  #     - 8083:8080

  proxy:
    image: nginx
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'

volumes:
  database:
  files:
