version: '3.8'

services:
  example-frontend:
    build:
      context: ./example-frontend
    ports:
      - 5000:5000

  example-backend:
    build:
      context: ./example-backend
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
