version: '3.8'

services:
  express-app:
    image: tomi12345/express-app:latest
    ports:
      - 8080:8080
    container_name: express-app

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: --cleanup express-app
