version: '3.8'

services:
  frontend:
    build: ./frontend
    # ports:
    #   - 4200:4200
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: angular-frontend

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app
    # ports:
    #   - '8000:8000'
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    container_name: django-server

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: django-postgres

  proxy:
    image: nginx
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'

volumes:
  node_modules:
  data:
  backend:
